### ISSUE TITLE
Add cloud discovery for google compute engine

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-cloud-gce#1]
Google Compute Engine VM discovery allows to use the google APIs to perform automatic discovery (similar to multicast in non hostile
multicast environments). Here is a simple sample configuration:

``` yaml
  cloud:
      gce:
          project_id: <your-google-project-id>
          zone: <your-zone>
  discovery:
          type: gce
```
## How to start (short story)
- Create Google Compute Engine instance
- Install Elasticsearch
- Install Google Compute Engine Cloud plugin
- Modify `elasticsearch.yml` file
- Start Elasticsearch
